config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get '/voz', to: 'static_pages#voz', as: 'voz'
  get '/word', to: 'static_pages#word', as: 'word'
  post '/word', to: 'static_pages#new_word'
  get '/video', to: 'static_pages#video', as: 'video'
  post '/video', to: 'static_pages#new_video'
  get '/morse', to: 'static_pages#morse', as: 'morse'
  post '/morse', to: 'static_pages#new_morse'
  match '/users/:id/finish_signup', to: 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_oauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource ? signed_in_resource : identity.user

    if user.nil?
      email = auth.info.email
      user = User.find_by(email: email) if email

      # Create the user if it's a new registration
      if user.nil?
        password = Devise.friendly_token[0,20]
        if auth.provider == 'facebook'
          user = User.new(
            email: email ? email : "#{auth.uid}@change-me.com",
            password: password,
            password_confirmation: password
          )
        elsif auth.provider == 'twitter'
          user = User.new(
            email: "#{auth.uid}@change-me.com",
            password: password,
            password_confirmation: password
          )
        end
      end
      user.save!
    end

    if identity.user != user
      identity.user = user
      identity.save!
    end

    user
  end

  def email_verified?
    if self.email
      if self.email.split('@')[1] == 'change-me.com'
        return false
      else
        return true
      end
    else
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.find_for_oauth(env["omniauth.auth"], current_user)

    if @user.persisted? # Chequea que nuestro usuario se haya guardado en la base de datos y no sea una instancia superficial
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "facebook".capitalize) if is_navigational_format?
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def after_sign_in_path_for(resource) # Revisa después de cada login si el mail del usuario es válido
    if resource.email_verified?
      super resource # Acción por defecto de Devise (si no está configurada, va al root_path)
    else
      finish_signup_path(resource)
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
  def voz
    #redirect_to '/voz'
  end
  def video
    #render 'video'
  end
  def new_video
    #guardar el parametro del objeto
    video = params[:video][:palabra]
    uri = URI('http://transmors.hol.es/vid.php?')
    params = { :tex => "#{video}" }
    uri.query = URI.encode_www_form(params)

    res = Net::HTTP.get_response(uri)
    render plain: "#{res.body}"
    #guargar en una variable lo que regrese
    # resp = Unirest.get('http://transmors.hol.es/vid.php?', parameters: {:tex => "#{video}"})
    #Mandar a la vista lo que regreso y ponerlo en el body
    #con ajax se agregara a una parte de la vista
    # render plain: "#{resp.body}"
  end
  def morse
  end
  def new_morse
    word = params[:morse][:palabra]
    #guargar en una variable lo que regrese
    resp = Unirest.get('http://transmors.hol.es/mor.php?', parameters: {:tex => "#{word}"})
    #Mandar a la vista lo que regreso y ponerlo en el body
    #con ajax se agregara a una parte de la vista
    render plain: "#{resp.body}"
  end
  #Renderear el formulario
  def word
    #redirect_to '/word'
  end
  #Metodo para jalar lo que regrese el web service
  def new_word
    #guardar el parametro del objeto
    word = params[:word][:palabra]
    #guargar en una variable lo que regrese
    resp = Unirest.get('http://transmors.hol.es/new.php?', parameters: {:tex => "#{word}"})
    #Mandar a la vista lo que regreso y ponerlo en el body
    #con ajax se agregara a una parte de la vista
    render plain: "#{resp.body}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def finish_signup
    if request.patch? && params[:user] # Revisa si el request es de tipo patch, es decir, llenaron el formulario y lo ingresaron
      @user = User.find(params[:id])

      if @user.update(user_params)
        sign_in(@user, :bypass => true)
        redirect_to root_path, notice: 'Hemos guardado tu email correctamente.'
      else
        @show_errors = true
      end
    end
  end

  private
    def user_params
      accessible = [ :name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("logo.jpg"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Log in", new_user_session_path, id: "login" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prueba</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src='https://code.responsivevoice.org/responsivevoice.js'></script>
</head>
<body>
  <%= render '/layouts/header' %>
  <%= yield %>


  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBIVgGMSIRWxmaxptMrZb2hyLwnOWylB4U&callback=initMap"
      async defer></script>
</body>
</html>

app/views/static_pages/index.html.erb
<div class="row">
  <div class="col-xs-1 col-sm-2 "><br></div>
  <div class="col-xs-10 col-sm-8 box">
    <center>
      <h1>TapSee</h1>
      <div class="row">
        <div class="col-xs-10 col-sm-6">
          <%= link_to 'Generador de voz', voz_path, class: "btn btn-info"  %><br>
        </div>
        <div class="col-xs-10 col-sm-6">
           <%= link_to 'Español a Morse', word_path, class: "btn btn-info" %><br>
         </div>
      </div>
      <br>
      <div class="row">
        <div class="col-xs-10 col-sm-6">
          <%= link_to 'Generador de video', video_path, class: "btn btn-info" %><br>
        </div>
        <div class="col-xs-10 col-sm-6">
          <%= link_to 'Morse a español', morse_path, class: "btn btn-info" %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-md-12">
          <%= link_to 'Voz', voz_path, class: "btn btn-info" %>
        </div>

      </div>
    </center>
  </div>
  <div class="col-xs-1 col-md-2"></div>
</div>

app/views/static_pages/login.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/static_pages/morse.html.erb
<div class="row">
  <div class="col-xs-1 col-sm-4"><br></div>
  <div class="col-xs-10 col-sm-4 box">
    <%= form_for :morse, :html => {:id => "morseform"} do |f| %>
      <%= f.label :Morse_a_español, class: "form-control" %> </br>
      <%= f.text_field :palabra, class: "form-control" %><br/>
      <%= f.submit "Cambiar a morse", class: "btn btn-success" %>
    <% end %>
    <p>
      Palabra en Español:
    </p>
    <div id="morse">
    </div>
  </div>
  <div class="col-xs-1 col-sm-4"></div>
</div>

app/views/static_pages/video.html.erb
<div class="row">
  <div class="col-xs-1 col-sm-2"><br></div>
  <div class="col-xs-10 col-sm-8 box">
    <%= form_for :video, :html => {:id => "videoform"} do |f| %>
      <%= f.label :Ingrese_palabra, class: "form-control" %> </br>
      <%= f.text_field :palabra, class: "form-control" %><br/>
      <%= f.submit "Mostrar señas", class: "btn btn-success" %>
    <% end %>
    <p>
      señas de la letra
    </p><div class="amor">


    <div id="tapar">
      <br>
    </div>
    <div id="video">
<!-- Copy to where you want to display the video player -->
      <script type="text/javascript" src="http://transmors.hol.es/js/jquery.js"></script>
      <script type="text/javascript" src="http://transmors.hol.es/js/magichtmlipadvideo.js"></script>
      <script type="text/javascript" src="http://transmors.hol.es/js/initipadvideo.js"></script>
      <div id="magichtmlvideoplayer">
      <embed id="perra" src="http://transmors.hol.es/asd.swf" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer"  quality="high" allowscriptaccess="always" wmode="transparent" allowFullScreen="true" align="middle" width="640" height="360"></embed>
      </div>
      </div>
<!-- End of video player codes -->
    </div>

  </div>
  <div class="col-xs-1 col-sm-2"></div>
</div>

app/views/static_pages/voz.html.erb
<div class="row">
  <div class="col-xs-1 col-sm-2 "><br></div>
  <div class="col-xs-10 col-sm-8 box">
    <!--Codigo para pasar de texto a voz-->
    <script src="https://code.responsivevoice.org/responsivevoice.js"></script>
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>

    <textarea id="text" cols="45" rows="3">Hello world</textarea>
    <br>
    <select id="voiceselection"></select>
    <br>
    <input
      onclick="responsiveVoice.speak($('#text').val(),$('#voiceselection').val());"
      type="button"
      value="Play"
    />

    <script>
            //Populate voice selection dropdown
            var voicelist = responsiveVoice.getVoices();
            var vselect = $("#voiceselection");
            $.each(voicelist, function() {
                    vselect.append($("<option />").val(this.name).text(this.name));
            });
    </script></div>
  <div class="col-xs-1 col-md-2"></div>
</div>

app/views/static_pages/word.html.erb
<div class="row">
  <div class="col-xs-1 col-sm-4"><br></div>
  <div class="col-xs-10 col-sm-4 box">
    <%= form_for :word, :html => {:id => "wordform"} do |f| %>
      <%= f.label :Español_a_morse, class: "form-control" %> </br>
      <%= f.text_field :palabra, class: "form-control" %><br/>
      <%= f.submit "Cambiar a morse", class: "btn btn-success" %>
    <% end %>
    <p>
      Palabra en morse:
    </p>
    <div id="word">
    </div>
  </div>
  <div class="col-xs-1 col-sm-4"></div>
</div>

app/views/users/finish_signup.html.erb
<h1>Confirma tu Email</h1>

<%= form_for(current_user, as: 'user', url: finish_signup_path(current_user)) do |f| %>
  <% if @show_errors && current_user.errors.any? %>
    <h2>Errores encontrados:</h2>
    <ul>
      <% current_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email, autofocus: true, value: '', placeholder: 'Example: email@me.com' %>
  </div>

  <div>
    <%= f.submit 'Confirmar' %>
  </div>

<% end %>